name: Generate Podcast Feeds
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Push Repo
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            branch: ${{ github.ref}}
